
import java.text.SimpleDateFormat;
import java.util.Date;
public class Booking extends javax.swing.JFrame {

    public Booking() {
        initComponents();
        int i = 1;
       // while(i>0)
       {Date dNow = new Date( );
      SimpleDateFormat ft = 
      new SimpleDateFormat ("E yyyy.MM.dd 'at' hh:mm:ss a zzz");
t1.setText("Current Date: " + ft.format(dNow));}
     // System.out.println("Current Date: " + ft.format(dNow));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        arrival = new javax.swing.JComboBox();
        departure = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nAdults = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nInfants = new javax.swing.JComboBox();
        nChildren = new javax.swing.JComboBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        t1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setForeground(java.awt.Color.black);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture.PNG"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.orange));
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 128, 25));

        jLabel2.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 36));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Depart On");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Search flights");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 36));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("To ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 180, -1));

        arrival.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "New Delhi", "Frankfurt", "Los Angeles", "Dubai", "Mumbai", "Singapore", "London", "New York", "Prague", "Athens" }));
        arrival.setToolTipText("please select your destination\n");
        arrival.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrivalActionPerformed(evt);
            }
        });
        jPanel1.add(arrival, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 131, -1));

        departure.setForeground(new java.awt.Color(51, 51, 51));
        departure.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "New Delhi", "Frankfurt", "Los Angeles", "Dubai", "Mumbai", "Singapore", "London", "New York ", "Prague", "Athens" }));
        departure.setToolTipText("Please select your origin");
        departure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departureActionPerformed(evt);
            }
        });
        jPanel1.add(departure, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 124, -1));

        jLabel4.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("From");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, 80));

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 3, 18));
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Fly with us, Fly safe.....");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        nAdults.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        nAdults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nAdultsActionPerformed(evt);
            }
        });
        jPanel1.add(nAdults, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 57, -1));

        jLabel8.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 36));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Adults");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        jLabel9.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Infants");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, -1, -1));

        jLabel7.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 36));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Class");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, -1, -1));

        jLabel10.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 36));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Children");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, -1, -1));

        nInfants.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        nInfants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nInfantsActionPerformed(evt);
            }
        });
        jPanel1.add(nInfants, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 54, -1));

        nChildren.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        jPanel1.add(nChildren, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 53, -1));

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Economy");
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, -1, -1));

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Business");
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, -1, -1));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 500, 370));
        jPanel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 267, 113, -1));

        t1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aircraft_aviation_1440x900_47118.jpg"))); // NOI18N
        jPanel1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -90, 1450, 790));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void arrivalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrivalActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_arrivalActionPerformed

private void departureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departureActionPerformed

}//GEN-LAST:event_departureActionPerformed

private void nInfantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nInfantsActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_nInfantsActionPerformed

private void nAdultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nAdultsActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_nAdultsActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
/*String Origin = (String) departure.getSelectedItem();  
    String Destination = (String) arrival.getSelectedItem();
    
    try {
            Class.forName("com.mysql.jdbc.Driver");
       
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pro", "root", "peace");
            java.sql.Statement stmt = con.createStatement();
            String query1 = "select * from flights where Origin ='" + Origin + "'and Destination = '" + Destination +  "';";
            ResultSet rs = stmt.executeQuery(query1);
            rs.next();
            JOptionPane.showMessageDialog(null,rs.getString("fno") + rs.getString("Origin") + rs.getString("Destination"));
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        */
    String day,month,year;
    day
      new flightSelection().setVisible(true);
      this.dispose();
}//GEN-LAST:event_jButton1ActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Booking().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox arrival;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JComboBox departure;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JComboBox nAdults;
    public static javax.swing.JComboBox nChildren;
    public static javax.swing.JComboBox nInfants;
    private javax.swing.JLabel t1;
    public static javax.swing.JTextField txtDate;
    // End of variables declaration//GEN-END:variables
}
