
import java.sql.*;
import javax.swing.JOptionPane;


public class confirmPayment extends javax.swing.JFrame {
Connection con;
Statement stmt,stmtt;
ResultSet rs;
//String bno, name, age, gender, phone, date, f, bdate;
        
    public confirmPayment() {
        initComponents();
        try
        {
           con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pro", "root", "tiger");
            stmt = con.createStatement(); 
            stmtt = con.createStatement(); 
        }
        catch(Exception e)
        {
            
        }
        c1.setVisible(true);
        c2.setVisible(true);
        c3.setVisible(true);
        d1.setVisible(false);
        d2.setVisible(false);
        d3.setVisible(false);
        n1.setVisible(false);
        n2.setVisible(false);
        lc1.setVisible(true);
        lc2.setVisible(true);
        lc3.setVisible(true);
        ld1.setVisible(false);
        ld2.setVisible(false);
        ld3.setVisible(false);
        ln1.setVisible(false);
        ln2.setVisible(false);
        
        
             
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cr = new javax.swing.JRadioButton();
        dr = new javax.swing.JRadioButton();
        cn = new javax.swing.JRadioButton();
        c1 = new javax.swing.JTextField();
        c2 = new javax.swing.JTextField();
        c3 = new javax.swing.JTextField();
        d1 = new javax.swing.JTextField();
        d2 = new javax.swing.JTextField();
        d3 = new javax.swing.JTextField();
        n1 = new javax.swing.JTextField();
        n2 = new javax.swing.JTextField();
        lc1 = new javax.swing.JLabel();
        lc2 = new javax.swing.JLabel();
        lc3 = new javax.swing.JLabel();
        ld1 = new javax.swing.JLabel();
        ld2 = new javax.swing.JLabel();
        ld3 = new javax.swing.JLabel();
        ln1 = new javax.swing.JLabel();
        ln2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 24)); // NOI18N
        jLabel2.setText("Mode Of Payment");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        cr.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(cr);
        cr.setFont(new java.awt.Font("Book Antiqua", 0, 11)); // NOI18N
        cr.setText("Credit Card");
        cr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crMouseClicked(evt);
            }
        });
        cr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crActionPerformed(evt);
            }
        });
        jPanel2.add(cr, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 90, -1));

        buttonGroup1.add(dr);
        dr.setText("Online Banking");
        dr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drMouseClicked(evt);
            }
        });
        jPanel2.add(dr, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        buttonGroup1.add(cn);
        cn.setForeground(new java.awt.Color(102, 102, 102));
        cn.setText("Debit card");
        cn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cnMouseClicked(evt);
            }
        });
        jPanel2.add(cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        jPanel2.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 70, -1));
        jPanel2.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 70, -1));

        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        jPanel2.add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 70, -1));
        jPanel2.add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 90, -1));
        jPanel2.add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 90, -1));

        d3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d3ActionPerformed(evt);
            }
        });
        jPanel2.add(d3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 90, -1));
        jPanel2.add(n1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 130, -1));

        n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n2ActionPerformed(evt);
            }
        });
        jPanel2.add(n2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 130, -1));

        lc1.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 14)); // NOI18N
        lc1.setText("Number");
        jPanel2.add(lc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        lc2.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 14)); // NOI18N
        lc2.setText("CVV");
        jPanel2.add(lc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        lc3.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 14)); // NOI18N
        lc3.setText("Name");
        jPanel2.add(lc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        ld1.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 14)); // NOI18N
        ld1.setText("Number");
        jPanel2.add(ld1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        ld2.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 14)); // NOI18N
        ld2.setText("CVV");
        jPanel2.add(ld2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        ld3.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 14)); // NOI18N
        ld3.setText("Name");
        jPanel2.add(ld3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        ln1.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 14)); // NOI18N
        ln1.setText("Account Number");
        jPanel2.add(ln1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));

        ln2.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 14)); // NOI18N
        ln2.setText("Password");
        jPanel2.add(ln2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("BIRTH OF A HERO", 1, 24)); // NOI18N
        jButton1.setText("Pay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 403, 190, 50));

        jLabel3.setFont(new java.awt.Font("BIRTH OF A HERO", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\Sir\\Desktop\\Project\\Graphix\\random\\3206_airports.jpg")); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, -50, 880, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c3ActionPerformed

    private void d3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d3ActionPerformed

    private void n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n2ActionPerformed

    private void cnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnMouseClicked
d1.setVisible(true);
        d2.setVisible(true);
        d3.setVisible(true);
        ld1.setVisible(true);
        ld2.setVisible(true);
        ld3.setVisible(true);
        c1.setVisible(false);
        c2.setVisible(false);
        c3.setVisible(false);
lc1.setVisible(false);
        lc2.setVisible(false);
        lc3.setVisible(false);
 n1.setVisible(false);
        n2.setVisible(false);
ln1.setVisible(false);
        ln2.setVisible(false);
        
    }//GEN-LAST:event_cnMouseClicked

    private void drMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drMouseClicked
 n1.setVisible(true);
        n2.setVisible(true);
ln1.setVisible(true);
        ln2.setVisible(true);
        d1.setVisible(false);
        d2.setVisible(false);
        d3.setVisible(false);
        ld1.setVisible(false);
        ld2.setVisible(false);
        ld3.setVisible(false);
        c1.setVisible(false);
        c2.setVisible(false);
        c3.setVisible(false);
lc1.setVisible(false);
        lc2.setVisible(false);
        lc3.setVisible(false);
    }//GEN-LAST:event_drMouseClicked

    private void crMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crMouseClicked
 n1.setVisible(false);
        n2.setVisible(false);
ln1.setVisible(false);
        ln2.setVisible(false);
         d1.setVisible(false);
        d2.setVisible(false);
        d3.setVisible(false);
        ld1.setVisible(false);
        ld2.setVisible(false);
        ld3.setVisible(false);
          c1.setVisible(true);
        c2.setVisible(true);
        c3.setVisible(true);
          lc1.setVisible(true);
        lc2.setVisible(true);
        lc3.setVisible(true);
    }//GEN-LAST:event_crMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  try {
      String Input = mainClass.bid;
      String query1 = "select * from bookingdata where  bno ='" + Input +  "';";
      String[] bno, name, age, gender, phone, date, f, bdate,query,flightno;
      bno = new String[10];
      age = new String[10];
      gender = new String[10];
      phone = new String[10];
      date = new String[10];
      f = new String[10];
      bdate = new String[10];
       name = new String[10];
         query = new String[10]   ;
         flightno = new String[10];
      
      int i = 0;
      stmt.executeQuery(query1);
           rs = stmt.executeQuery(query1);
            while(rs.next())
            {i++;
                bno[i]= rs.getString("bno");
                name[i]= rs.getString("name");
                age[i] = rs.getString("age");
                gender[i]= rs.getString("gender");
                phone[i] = rs.getString("phone");
                date[i] = rs.getString("doj");
                f[i] = rs.getString("fare");
                bdate[i] = rs.getString("tob");
                flightno[i] = rs.getString("flightno");
            query[i] = "insert into bookingdetails values('" + bno[i] + "','" + name[i]+"'," + age[i]+",'" + gender[i] + "'," + phone[i] + ",'" + date[i] + "'," + f[i]+",'" +bdate[i]+"','" + flightno[i]  +"');";
               stmtt.executeUpdate(query[i]);
            }
           
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
 /* try
  {
      for (int i =0;i<=5;i++)
        Class.forName("com.mysql.jdbc.Driver");
     
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pro", "root", "tiger");
            java.sql.Statement stmt = con.createStatement();      
           stmt.executeUpdate(query);
           stmt.close();
            con.close();
              
  }
  catch(Exception e)
  {
      
  }
  
    */    JOptionPane.showMessageDialog(null,"Payment Confirmed!Your booking ID is : " + mainClass.bid + " .Please use it for future reference.");
   
new welcome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(confirmPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(confirmPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(confirmPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(confirmPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new confirmPayment().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField c1;
    private javax.swing.JTextField c2;
    private javax.swing.JTextField c3;
    private javax.swing.JRadioButton cn;
    private javax.swing.JRadioButton cr;
    private javax.swing.JTextField d1;
    private javax.swing.JTextField d2;
    private javax.swing.JTextField d3;
    private javax.swing.JRadioButton dr;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lc1;
    private javax.swing.JLabel lc2;
    private javax.swing.JLabel lc3;
    private javax.swing.JLabel ld1;
    private javax.swing.JLabel ld2;
    private javax.swing.JLabel ld3;
    private javax.swing.JLabel ln1;
    private javax.swing.JLabel ln2;
    private javax.swing.JTextField n1;
    private javax.swing.JTextField n2;
    // End of variables declaration//GEN-END:variables
}
